export const OBTENER_DATOS_USUARIOS = 'OBTENER_DATOS_USUARIOS'
export const CARGANDO_TABLA_DATOS_USUARIOS = 'CARGANDO_TABLA_DATOS_USUARIOS'
export const OBTENER_DATOS_PAISES = 'OBTENER_DATOS_PAISES'
export const OBTENER_DATOS_TIPOS_USUARIOS = 'OBTENER_DATOS_TIPOS_USUARIOS'