export const OBTENER_DATOS_PERMISOS = 'OBTENER_DATOS_PERMISOS'
export const CARGANDO_TABLA_DATOS_PERMISOS = 'CARGANDO_TABLA_DATOS_PERMISOS'
export const OBTENER_DATA_PERMISOS = 'OBTENER_DATA_PERMISOS'